version: "3.9"
services:
  api:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:8080/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3