name: Continuous Integration

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/poetry.lock') }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint, Type-Check & Test
        run: |
          echo "Executando linters e testes..."
          # Exemplo: substitua pelos comandos reais do seu projeto
          pip install pytest mypy ruff
          ruff check .
          mypy .
          pytest -v

      - name: Build Docker image (Validation only)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ github.repository }}:ci-test

      - name: Trivy security scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ github.repository }}:ci-test
          format: 'table'
          exit-code: '1'
