name: Continuous Deploy (AWS ECS)

on:
  workflow_run:
    workflows: ["Continuous Release"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Deploy new image to ECS
        id: deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ecs-task-definition.json
          service: ${{ secrets.ECS_SERVICE_NAME }}
          cluster: ${{ secrets.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true

      - name: Health Check
        run: |
          echo "Executando health check..."
          sleep 15
          if ! curl -fsS http://${{ secrets.ECS_SERVICE_URL }}/healthz; then
            echo "❌ Health check falhou, iniciando rollback..."
            aws ecs update-service \
              --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
              --service ${{ secrets.ECS_SERVICE_NAME }} \
              --force-new-deployment
            exit 1
          else
            echo "✅ Deploy bem-sucedido e aplicação saudável."
          fi
