name: Continuous Integration

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # NOVO PASSO PARA CORRIGIR O NOME DA IMAGEM
      - name: Prepare image name in lowercase
        id: string_converter
        run: echo "image_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint, Type-Check & Test
        env:
          PYTHONPATH: .
        run: |
          echo "Executando linters e testes..."
          ruff check src tests
          mypy tests
          pytest -v tests/

      - name: Build Docker image (Validation only)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile 
          push: false
          # CORREÇÃO: Usa a variável de saída do passo 'string_converter'
          tags: ${{ steps.string_converter.outputs.image_name }}:ci-test

      - name: Trivy security scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          # CORREÇÃO: Usa a mesma variável de saída
          image-ref: ${{ steps.string_converter.outputs.image_name }}:ci-test
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'